<?php

namespace ClassmapGenerator;

class Writer{

    private $format = 'indexed_array';

    public function useRequireFormat(){
        $this->format = 'require';
    }

    public function write(string $dirname, string $filename, Array $data):void {
        if(!is_dir($dirname)){
            throw new \InvalidArgumentException('$dirname must be a valid directory path.');   
        }
        
        if (strpbrk($filename, "\\/?%*:|\"<>") !== FALSE ) {
            throw new \InvalidArgumentException('$filename contains an illegal character.');
        }        

        $path = trim($dirname, '/');
        $path.= '/'.$filename;

        $content = "<?php \n\n";
        $content.= '// Generated by ClassmapGenerator at '.date('Y-m-d H:i:s');
        $content.= "\n";

        if($this->format == 'indexed_array'){
            $content.= 'return array(';
            foreach($data as $classname => $pathname){
                $spacer  = str_pad(" ", (50 - strlen($classname)), ' ');
                $content.= "\n    '{$classname}' {$spacer} => '{$pathname}',";  
            }
            $content.= "\n);";        
        }
        else{
            foreach($data as $classname => $pathname){
                $content.= "require '{$pathname}';\n";  
            }
        }

        file_put_contents($path, $content);
    }

}